package com.avatarduel.gui.event;

public enum Event {
    CHANGE_CARD_VIEW,
    UPDATE_POWER,
    DRAW_CARD,
    FLIP_CARDS,
    DISABLEPLAYER,
    ENABLEPLAYER,
    DISABLEPLAYERHANDS,
    ENABLEPLAYERHANDS,
    MAIN_PHASE,
    NEXT_PHASE,
    GOT_CARD,
    PASS_CARD,
    CARD_PLACED,
    PASS_SELECTED_CARD,
    PASS_SELECTED_PANEID,
    SELECTEDCARD,
    RESET_SELECT_CARD,
    DONE_ATTACK,
    ATTACHING_SKILL,
    MODIFYING_TYPE,
    MODIFYING_CHARACTER,
    MODIFYING_SKILL,
    SKILL_LOCATION,
    SKILL_PLACING,
    DISABLE_LAND_CARDS
}
