package com.avatarduel.gui.event;

public enum Event {
    CHANGE_CARD_VIEW,
    UPDATE_POWER,
    DRAW_CARD,
    FLIP_CARDS,
    DISABLEPLAYER,
    ENABLEPLAYER,
    DISABLEPLAYERHANDS,
    ENABLEPLAYERHANDS,
    MAIN_PHASE,
    NEXT_PHASE,
    GOT_CARD,
    PASS_CARD,
    CARD_PLACED,
    PASS_SELECTED_CARD,
    PASS_SELECTED_PANEID,
    SELECTEDCARD,
    DISABLE_LAND_CARDS
}
