package com.avatarduel.gui.event;

public enum Event {
    CHANGE_CARD_VIEW,
    UPDATE_POWER,
    DRAW_CARD,
    TAKE_HAND_CARD,
    DRAW_HAND_CARD,
    FLIP_CARDS,
    DISABLEPLAYER,
    ENABLEPLAYER,
    DISABLEPLAYERHANDS,
    ENABLEPLAYERHANDS,
    DRAW_PHASE,
    MAIN_PHASE,
    BATTLE_PHASE,
    NEXT_PHASE,
    CARD_PLACED_TO_FIELD,
    GOT_CARD,
    PASS_CARD,
    DISABLE_LAND_CARDS
}
