package com.avatarduel.view.event;

public enum Event {
    CHANGE_CARD_VIEW,
    UPDATE_POWER,
    DISABLEPLAYER,
    ENABLEPLAYER,
    GOT_CARD,
    PASS_CARD,
    CARD_PLACED,
    PASS_SELECTED_CARD,
    PASS_SELECTED_PANEID,
    SELECTEDCARD,
    RESET_SELECT_CARD,
    ATTACHING_SKILL,
    MODIFYING,
    MODIFY_LOCATION,
    SKILL_LOCATION,
    SKILL_PLACING
}
